import "./styles/app.scss"
import CustomNav from "./components/CustomNav/CustomNav"
import { Providers } from "./redux/provider"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <header><CustomNav /></header>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
